# Generated by Django 3.1.6 on 2021-04-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('Brandname', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('Brandstatus', models.CharField(choices=[('1', 'Available'), ('2', 'UnAvailable')], default='UnAvailable', max_length=256)),
            ],
            options={
                'ordering': ['Brandname'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Categoryname', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('Categorystatus', models.CharField(choices=[('1', 'Available'), ('2', 'UnAvailable')], default='UnAvailable', max_length=256)),
            ],
            options={
                'ordering': ['Categoryname'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Productname', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('Productstatus', models.CharField(choices=[('1', 'Available'), ('2', 'UnAvailable')], default='UnAvailable', max_length=256)),
                ('AvailableQuantity', models.PositiveIntegerField(default=0)),
                ('ProductBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.brand')),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.category')),
            ],
            options={
                'ordering': ['Productname'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderedQuantity', models.PositiveIntegerField(default=1)),
                ('OrderedCustomer', models.CharField(max_length=256)),
                ('OrderedProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
    ]
