# Generated by Django 3.1.6 on 2021-04-14 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-OrderedDate']},
        ),
        migrations.AddField(
            model_name='order',
            name='OrderedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='stock.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='stock.category'),
        ),
    ]
